name: Build Binaries (Linux + Windows cross)

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  linux-and-windows-cross:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build Linux executable
        run: python -m pip install --upgrade pip pyinstaller
      - run: pyinstaller --onefile --name epub-series-editor-linux epub_series_editor.py

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: epub-series-editor-linux
          path: |
            dist/epub-series-editor-linux*
          if-no-files-found: error

      - name: Build Windows executable (cross via Wine)
        uses: addnab/docker-run-action@v3
        with:
          image: cdrx/pyinstaller-windows:python3
          options: -v ${{ github.workspace }}:/src
          run: pyinstaller --onefile --name epub-series-editor-win epub_series_editor.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: epub-series-editor-windows
          path: |
            dist/epub-series-editor-win.exe
          if-no-files-found: error

