name: Build Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install PyInstaller
        run: python -m pip install --upgrade pip pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --name epub-series-editor epub_series_editor.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: epub-series-editor-${{ runner.os }}
          path: |
            dist/epub-series-editor*
          if-no-files-found: error

